/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/cars": {
    /** Returns all the cars */
    get: {
      parameters: {
        query: {
          /** The manufacturer to filter by */
          manufacturer?: string;
          /** The color to filter by */
          color?: string;
          /** When this parameter is present the cars are sorted by mileage. The value of this parameter defines the sorting order */
          sort?: "asc" | "des";
          /** Results are paginated. This parameter defines the number of the page to return */
          page?: number;
        };
      };
      responses: {
        /** A list of cars */
        200: {
          content: {
            "application/json": {
              cars?: components["schemas"]["Car"][];
              /** @example 2 */
              totalPageCount?: number;
              /** @example 16 */
              totalCarsCount?: number;
            };
          };
        };
      };
    };
  };
  "/api/cars/{stockNumber}": {
    /** Returns one car */
    get: {
      parameters: {
        path: {
          /** The unique stock number of a car */
          stockNumber: number;
        };
      };
      responses: {
        /** A car */
        200: {
          content: {
            "application/json": {
              car?: components["schemas"]["Car"];
            };
          };
        };
        /** A car with the specified stock number was not found */
        400: {
          content: {
            "text/plain": string;
          };
        };
      };
    };
  };
  "/api/colors": {
    /** Returns all the colors */
    get: {
      responses: {
        /** A list of colors */
        200: {
          content: {
            "application/json": {
              colors?: components["schemas"]["Color"][];
            };
          };
        };
      };
    };
  };
  "/api/manufacturers": {
    /** Returns all the manufacturers */
    get: {
      responses: {
        /** A list of car manufacturers */
        200: {
          content: {
            "application/json": {
              manufacturers?: components["schemas"]["Manufacturer"][];
            };
          };
        };
      };
    };
  };
}

export interface components {
  schemas: {
    /** @example white */
    Color: string;
    Manufacturer: {
      /** @example Fiat */
      name?: string;
      models?: {
        /** @example Marea */
        name?: string;
      }[];
    };
    Car: {
      /** @example 41400 */
      stockNumber?: number;
      /** @example Fiat */
      manufacturerName?: string;
      /** @example Marea */
      modelName?: string;
      mileage?: {
        /** @example 100141 */
        number?: number;
        /** @enum {string} */
        unit?: "km" | "mi";
      };
      /** @enum {string} */
      fuelType?: "Diesel" | "Petrol";
      color?: components["schemas"]["Color"];
      /** @example http://localhost:3001/car.svg */
      pictureUrl?: string;
    };
  };
}

export interface operations {}

export interface external {}
